### PR TITLE
Added a challenge to map plain arrays of string

### PR DESCRIPTION
**Pull request by vemonet**
Hi, I added a challenge related to mapping plain arrays of string: explained the issue in the readme, added an example input JSON, and the expected output turtle file

The challenge has been discussed in this issue: https://github.com/RMLio/rmlmapper-java/issues/95

### CODE REVIEW

**Comment by bjdmeest** [comment]
@vemonet thanks! I have the feeling this is also related to https://github.com/RMLio/rml-test-cases/issues/14 , could you verify and maybe add that link if that's the case? Looks good otherwise!

**Comment by pmaria** [comment]
I don't think anything new in RML is necessary for this to work. You can use `@` in JSONPath to get the current node.
I just tried the following mapping in [CARML](https://github.com/carml/carml)
```
<#Ingredient> a rr:TriplesMap ;
  rml:logicalSource [
    rml:source [ a carml:Stream ] ;
    rml:iterator "$[*].ingredients[*]" ;
    rml:referenceFormulation ql:JSONPath ;
  ] ;
  rr:subjectMap [
    rr:template "http://example.com/{@}"
  ] ;
  rr:predicateObjectMap [
    rr:predicate ex:label ;
    rr:objectMap [
      rml:reference "@" ;
    ] ;
  ] ;
.

<#Recipe> a rr:TriplesMap ;
  rml:logicalSource [
    rml:source [ a carml:Stream ] ;
    rml:iterator "$[*]" ;
    rml:referenceFormulation ql:JSONPath ;
  ] ;
  rr:subjectMap [
    rr:template "http://example.com/recipe{id}"
  ] ;
  rr:predicateObjectMap [
    rr:predicate ex:ingredients ;
    rr:objectMap [
      rr:template "http://example.com/{ingredients[*]}" ;
    ] ;
  ] ;
.
```
and it leads to 
```
<http://example.com/garlic> <http://example.com/label> "garlic" .

<http://example.com/pepper> <http://example.com/label> "pepper" .

<http://example.com/salt> <http://example.com/label> "salt" .

<http://example.com/tomatoes> <http://example.com/label> "tomatoes" .

<http://example.com/recipe1> <http://example.com/ingredients> <http://example.com/garlic>,
    <http://example.com/pepper> .

<http://example.com/recipe2> <http://example.com/ingredients> <http://example.com/salt>,
    <http://example.com/tomatoes> .

```

**Comment by vemonet** [comment]
Thanks a lot @pmaria ! This is exactly what I was looking for

But it is not straightforward to figure out, I don't know all the details of the JSONPath language (and it is not completely standardized currently), and I could not find a test using `@`

It would be interesting to have an example in the RML specifications

**Comment by vemonet** [comment]
@pmaria  I tried your solution with the reference implementation of the RML mapper, but this does not work

`ingredients.json`:

```json
[
    {
      "id": 1,
      "ingredients": [
        "garlic",
        "pepper"
      ]
    },
    {
      "id": 2,
      "ingredients": [
        "salt",
        "tomatoes"
      ]
    }
  ]
```

YARRRML mappings:
```yaml
prefixes:
  grel: "http://users.ugent.be/~bjdmeest/function/grel.ttl#"
  rdfs: "http://www.w3.org/2000/01/rdf-schema#"
  fo: "http://purl.org/ontology/fo/"
mappings:
  ingredients:
    sources:
      - ['ingredients.json~jsonpath', "$.[*].ingredients[*]"]
    s: fo:ingredient/$(@)
    po:
      - [rdfs:label, $(@)]
```

RML mapping (using Matey):

```ttl
@prefix rr: <http://www.w3.org/ns/r2rml#>.
@prefix rml: <http://semweb.mmlab.be/ns/rml#>.
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix ql: <http://semweb.mmlab.be/ns/ql#>.
@prefix map: <http://mapping.example.com/>.

map:map_ingredients_000 rml:logicalSource map:source_000;
    a rr:TriplesMap;
    rdfs:label "ingredients";
    rr:subjectMap map:s_000;
    rr:predicateObjectMap map:pom_000.
map:om_000 a rr:ObjectMap;
    rml:reference "@";
    rr:termType rr:Literal.
map:pm_000 a rr:PredicateMap;
    rr:constant rdfs:label.
map:pom_000 a rr:PredicateObjectMap;
    rr:predicateMap map:pm_000;
    rr:objectMap map:om_000.
map:rules_000 a <http://rdfs.org/ns/void#Dataset>;
    <http://rdfs.org/ns/void#exampleResource> map:map_ingredients_000.
map:s_000 a rr:SubjectMap;
    rr:template "http://purl.org/ontology/fo/ingredient/{@}".
map:source_000 a rml:LogicalSource;
    rml:source "ingredients.json";
    rml:iterator "$.[*].ingredients[*]";
    rml:referenceFormulation ql:JSONPath.
```

This does not return a triple (only the prefixes declaration)

I ran it using the latest RML mapper https://github.com/RMLio/rmlmapper-java/releases

```bash
java -jar ~/bin/rmlmapper.jar -m mappings.rml.ttl -o output.ttl -s turtle
```

@thomas-delva is there a plan to support `@` from JSONPath in RML?

**Comment by vemonet** [comment]
@bjdmeest it does not seems like there are any tests cases corresponding

https://github.com/RMLio/rml-test-cases/blob/master/test-cases/RMLTC0010a-JSON/country_info.json
https://github.com/RMLio/rml-test-cases/blob/master/test-cases/RMLTC0010b-JSON/country_info.json
https://github.com/RMLio/rml-test-cases/blob/master/test-cases/RMLTC0010c-JSON/country_info.json

```json
{
  "countries": [{
    "Country Code": 1,
    "Name":"Bolivia, Plurinational State of",
    "ISO 3166": "BO"
  }, {
    "Country Code": 2,
    "Name":"Ireland",
    "ISO 3166": "IE"
  }, {
    "Country Code": 3,
    "Name":"Saint Martin (French part)",
    "ISO 3166": "MF"
  }]
}
```


It seems like this JSONPath functionality (`@`) has not been considered when defining the RML implementation and test cases

**Comment by pmaria** [comment]
>@pmaria I tried your solution with the reference implementation of the RML mapper, but this does not work

Ah that's too bad. That might be a bug then.

**Comment by pmaria** [comment]
> But it is not straightforward to figure out, I don't know all the details of the JSONPath language (and it is not completely standardized currently), and I could not find a test using @

Indeed. This can be problematic, however the use of `@` could be considered standard across implementations. Both RML Mapper and Carml use the Jayway implementation. See [its list of operators](https://github.com/json-path/JsonPath#operators).

The good news is, there is currently a push for standardization of JSONPath triggered by [this comparison initiative](https://github.com/cburgmer/json-path-comparison) and an [emerging specification](https://ietf-wg-jsonpath.github.io/draft-ietf-jsonpath-jsonpath/.)

**Comment by vemonet** [comment]
As discussed, this is not really a challenge, and more of a test case to handle within RML implementations

The test has been added to the RMLmapper test cases in https://github.com/RMLio/rmlmapper-java/pull/110 , and supporting `@`  implemented in rmlmapper-java

**Pull request closed without merging**
